# Generated by Django 4.2.7 on 2023-11-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
